#!/usr/bin/env python3
"""Emit webapp/frontend/js/snippets/*.r.txt — full plumber/viz cores, runnable under POST /api/exec/user_r."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PL = ROOT / "webapp" / "backend" / "plumber.R"
VZ = ROOT / "webapp" / "backend" / "helpers" / "viz.R"
OUT = ROOT / "webapp" / "frontend" / "js" / "snippets"

COMMON_HEAD = (
    "# Auto-generated by webapp/scripts/build_code_snippets.py\n"
    "# session_id (+ experiment) come from POST /api/user_r/run (Code Lab).\n"
)

JSON_LINE = re.compile(r"^\s*b\s*<-\s*jsonlite::fromJSON\(req\$postBody\)\s*$", re.MULTILINE)

EXP_GUARD = """if (!exists("experiment", inherits = FALSE) || is.null(experiment) || !nzchar(as.character(experiment)[1]))
  stop("experiment required: set in Code Lab or assign experiment <- 'YourExp'")
"""


def slurp(path: Path, lo: int, hi: int) -> str:
    lines = path.read_text(encoding="utf-8").splitlines()
    return "\n".join(lines[lo - 1 : hi]) + "\n"


def dedent_block(s: str) -> str:
    lines = s.splitlines()
    nonempty = [ln for ln in lines if ln.strip()]
    if not nonempty:
        return ""
    indents = [len(ln) - len(ln.lstrip(" ")) for ln in nonempty]
    m = min(indents)
    if m <= 0:
        return "\n".join(lines).rstrip() + "\n"
    out = []
    for ln in lines:
        if not ln.strip():
            out.append("")
        else:
            out.append(ln[m:] if len(ln) >= m else ln.lstrip())
    return "\n".join(out).rstrip() + "\n"


def strip_json_inject(s: str, b_prefix: str | None) -> str:
    s = dedent_block(s)
    s = JSON_LINE.sub("", s)
    if b_prefix:
        s = b_prefix.rstrip() + "\n" + s
    return s


def write(name: str, body: str, note: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    head = COMMON_HEAD + f"# {note}\n\n"
    (OUT / name).write_text(head + body.rstrip() + "\n", encoding="utf-8")
    print("wrote", name)


# (file, path, lo, hi, note, b_prefix) — slice includes jsonlite line; b_prefix inserted after removal.
SLICES: list[tuple[str, Path, int, int, str, str | None]] = [
    (
        "preparation__prep-filter.r.txt",
        PL,
        480,
        521,
        "plumber.R prepare/filter",
        EXP_GUARD
        + """b <- list(
  session_id = session_id,
  experiment = as.character(experiment)[1],
  min_count = 0, min_samples = 0L,
  min_detect_rate = NA_real_, max_detect_rate = NA_real_,
  min_prevalence = 0, max_na = 1, prepare_mode = "stack"
)
""",
    ),
    (
        "preparation__prep-normalize.r.txt",
        PL,
        530,
        547,
        "plumber.R prepare/normalize",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  method = "rclr", prepare_mode = "stack"
)
""",
    ),
    (
        "preparation__prep-impute.r.txt",
        PL,
        556,
        573,
        "plumber.R prepare/impute",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  method = "knn", prepare_mode = "stack"
)
""",
    ),
    (
        "preparation__prep-rarefy.r.txt",
        PL,
        582,
        601,
        "plumber.R prepare/rarefy",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  sample_size = 0L, prepare_mode = "stack"
)
""",
    ),
    (
        "preparation__prep-collapse.r.txt",
        PL,
        610,
        629,
        "plumber.R prepare/collapse",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  taxa_level = "Genus", prepare_mode = "stack"
)
""",
    ),
    (
        "preparation__prep-m16s-taxonomy.r.txt",
        PL,
        925,
        944,
        "plumber.R m16s prepare/taxonomy",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  collapse_level = "Genus", min_total_abundance = 0, drop_unassigned = TRUE,
  keep_top_n = 0L, tax_sep = ";", normalize_method = NULL
)
""",
    ),
    (
        "analysis__ana-alpha.r.txt",
        PL,
        953,
        965,
        "plumber.R analyze/alpha",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  method = "shannon", source = "current"
)
""",
    ),
    (
        "analysis__ana-diff.r.txt",
        PL,
        974,
        993,
        "plumber.R analyze/differential",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  method = "DESeq2", group_var = NULL, ref_group = NULL, test_group = NULL,
  filter_low = TRUE, subset_two_groups = TRUE, cores = "auto"
)
""",
    ),
    (
        "analysis__ana-dim.r.txt",
        PL,
        1207,
        1218,
        "plumber.R analyze/dimension",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  method = "PCA"
)
""",
    ),
    (
        "analysis__ana-cor.r.txt",
        PL,
        1227,
        1238,
        "plumber.R analyze/correlation",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  use = "spearman"
)
""",
    ),
    (
        "analysis__ana-cluster.r.txt",
        PL,
        1247,
        1259,
        "plumber.R analyze/cluster",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  method = "hclust", k = 3L
)
""",
    ),
    (
        "analysis__ana-marker.r.txt",
        PL,
        1268,
        1282,
        "plumber.R analyze/marker",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  method = "randomForest", group_var = NULL, ref_group = NULL, test_group = NULL
)
""",
    ),
    (
        "analysis__ana-enrich.r.txt",
        PL,
        1291,
        1320,
        "plumber.R analyze/enrichment",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  database = "KEGG", organism = "hsa", fc_cutoff = 1.0, p_cutoff = 0.05,
  use_padj = TRUE, direction = "both", top_n = 20L
)
""",
    ),
    (
        "analysis__ana-network.r.txt",
        PL,
        1394,
        1401,
        "plumber.R analyze/network",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  method = "spearman", cutoff = 0.6
)
""",
    ),
    (
        "clinical__reorient.r.txt",
        PL,
        244,
        250,
        "plumber.R clinical/reorient",
        """b <- list(session_id = session_id, mode = "auto")
""",
    ),
    (
        "clinical__three_line.r.txt",
        PL,
        2111,
        2169,
        "plumber.R clinical/three_line",
        """b <- list(
  session_id = session_id,
  experiment = if (exists("experiment", inherits = FALSE) && !is.null(experiment)) as.character(experiment)[1] else NULL,
  source = "standalone", group_var = NULL, skip_high_cardinality = TRUE,
  max_levels = 20L, table_engine = "gtsummary"
)
""",
    ),
    (
        "clinical__systematic.r.txt",
        PL,
        2172,
        2199,
        "plumber.R clinical/systematic_summary",
        """b <- list(
  session_id = session_id,
  experiment = if (exists("experiment", inherits = FALSE) && !is.null(experiment)) as.character(experiment)[1] else NULL,
  source = "standalone", group_var = NULL, skip_high_cardinality = TRUE,
  max_levels = 20L, table_engine = "gtsummary", cohort_filter = NULL
)
""",
    ),
    (
        "clinical__cor.r.txt",
        PL,
        2215,
        2239,
        "plumber.R clinical/cor",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  traits = c("REPLACE_WITH_NUMERIC_CLINICAL_COL"),
  method = "spearman", top_n_features = 30L, p_adjust = "BH",
  clinical_source = "experiment"
)
""",
    ),
    (
        "clinical__fitline.r.txt",
        PL,
        2249,
        2271,
        "plumber.R clinical/fitline",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  feature = "REPLACE_FEATURE", trait = "REPLACE_TRAIT", group = NULL,
  method = "lm", log_y = FALSE, clinical_source = "experiment"
)
""",
    ),
    (
        "clinical__wgcna.r.txt",
        PL,
        2282,
        2305,
        "plumber.R clinical/wgcna async",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  traits = c("REPLACE_TRAIT"), min_module_size = 30L, clinical_source = "experiment"
)
""",
    ),
    (
        "clinical__joint.r.txt",
        PL,
        2315,
        2340,
        "plumber.R clinical/multiomics_joint",
        EXP_GUARD
        + """b <- list(
  session_id = session_id,
  exp_a = as.character(experiment)[1],
  exp_b = "REPLACE_SECOND_EXPERIMENT",
  traits = NULL, method = "spearman", top_n = 20L, clinical_source = "experiment"
)
""",
    ),
    (
        "clinical__marker_model.r.txt",
        PL,
        2390,
        2420,
        "plumber.R clinical/marker_model",
        """b <- list(
  session_id = session_id,
  experiments = c("REPLACE_EXPERIMENT"),
  outcome_var = "REPLACE_BINARY_OUTCOME",
  positive_class = NULL,
  methods = c("randomForest", "lasso", "xgboost"),
  clinical_source = "experiment",
  include_clinical_numeric = TRUE,
  max_features_per_omics = 200L,
  top_n = 30L,
  validation_fraction = 0.3,
  seed = 123L
)
""",
    ),
    (
        "runall__runall-rnaseq.r.txt",
        PL,
        1094,
        1113,
        "plumber.R rnaseq run_all",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  group_var = "Group", ref_group = NULL, test_group = NULL, organism = "mmu",
  fc_cutoff = 1.0, p_cutoff = 0.05, use_padj = TRUE, min_row_sum = 0,
  do_enrichment = TRUE
)
""",
    ),
    (
        "runall__runall-m16s.r.txt",
        PL,
        1122,
        1137,
        "plumber.R m16s run_all",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  group_var = NULL, taxonomy_level = "Genus", alpha_index = "shannon",
  beta_method = "bray", ord_method = "PCoA"
)
""",
    ),
    (
        "visualization__viz-m16s-sankey.r.txt",
        PL,
        1604,
        1628,
        "plumber.R m16s sankey",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  tax_sep = ";", from_level = "Phylum", to_level = "Genus",
  top_n = 25L, width = 10, height = 6,
  color_panel = NULL, custom_colors = NULL
)
""",
    ),
    (
        "visualization__viz-m16s-network.r.txt",
        PL,
        1637,
        1655,
        "plumber.R m16s network",
        EXP_GUARD
        + """b <- list(
  session_id = session_id, experiment = as.character(experiment)[1],
  method = "spearman", cutoff = 0.6, top_n = 40L,
  width = 8, height = 8
)
""",
    ),
]

VIZ_SLICES: list[tuple[str, Path, int, int, str]] = [
    ("visualization__viz-barplot.r.txt", VZ, 117, 201, "viz.R make_barplot"),
    ("visualization__viz-boxplot.r.txt", VZ, 206, 303, "viz.R make_boxplot"),
    ("visualization__viz-heatmap.r.txt", VZ, 304, 452, "viz.R make_heatmap"),
    ("visualization__viz-volcano.r.txt", VZ, 453, 806, "viz.R make_volcano"),
    ("visualization__viz-structure.r.txt", VZ, 961, 1023, "viz.R make_structure"),
    ("visualization__viz-alpha.r.txt", VZ, 1024, 1119, "viz.R make_alpha_plot"),
]

VIZ_SCATTER_BODY = """make_scatter(
  session_id, experiment,
  group = NULL, dim1 = 1L, dim2 = 2L,
  width = 9, height = 7, proj_width = 7, proj_height = 4.5,
  groups_include = NULL, ordination = "auto",
  color_panel = NULL, custom_colors = NULL
)
"""


def clinical_overview_body() -> str:
    return (
        EXP_GUARD
        + "\n"
        + dedent_block(
            """
# --- GET /api/clinical/vars/:session_id/:experiment ---
df_exp <- list_clinical_vars(session_id, experiment)
out_exp <- list(success = TRUE, n_rows = nrow(df_exp), data = df_exp)

# --- GET /api/clinical/vars_standalone/:session_id ---
df_standalone <- list_clinical_vars_standalone(session_id)
out_standalone <- list(success = TRUE, n_rows = nrow(df_standalone), data = df_standalone)

list(experiment_vars = out_exp, standalone_vars = out_standalone)
"""
        )
    )


def tx_visual_bundle() -> str:
    exp = "as.character(experiment)[1]"
    b_h = f"""b <- list(
  session_id = session_id, experiment = {exp},
  group = NULL, top_n = 50L, features = NULL, cluster_rows = TRUE,
  cluster_cols = TRUE, show_gene_names = NULL, font_size = 11,
  color_panel = NULL, custom_colors = NULL
)
"""
    heatmap = strip_json_inject(slurp(PL, 1414, 1433), b_h)
    b_v = f"""b <- list(
  session_id = session_id, experiment = {exp},
  fc_cutoff = 1.0, p_cutoff = 0.05, color_panel = NULL, custom_colors = NULL
)
"""
    volcano = strip_json_inject(slurp(PL, 1442, 1452), b_v)
    return (
        EXP_GUARD
        + "\n# --- POST /api/workflows/transcriptomics/visualize/heatmap ---\n"
        + heatmap
        + "\n\n# --- POST /api/workflows/transcriptomics/visualize/volcano ---\n"
        + volcano
    )


def mgx_visual_bundle() -> str:
    exp = "as.character(experiment)[1]"
    b_h = f"""b <- list(
  session_id = session_id, experiment = {exp},
  group = NULL, top_n = 50L, features = NULL, cluster_rows = TRUE,
  cluster_cols = TRUE, show_gene_names = NULL, font_size = 11,
  color_panel = NULL, custom_colors = NULL
)
"""
    heatmap = strip_json_inject(slurp(PL, 1461, 1480), b_h)
    b_v = f"""b <- list(
  session_id = session_id, experiment = {exp},
  fc_cutoff = 1.0, p_cutoff = 0.05, color_panel = NULL, custom_colors = NULL
)
"""
    volcano = strip_json_inject(slurp(PL, 1489, 1499), b_v)
    return (
        EXP_GUARD
        + "\n# --- POST /api/workflows/metagenomics/visualize/heatmap ---\n"
        + heatmap
        + "\n\n# --- POST /api/workflows/metagenomics/visualize/volcano ---\n"
        + volcano
    )


def tx_workflow_bundle() -> str:
    parts = [EXP_GUARD + "\n"]
    exp = "as.character(experiment)[1]"
    blocks: list[tuple[str, int, int, str]] = [
        (
            "POST /api/workflows/transcriptomics/profile",
            671,
            676,
            f"b <- list(session_id = session_id, experiment = {exp}, assay_hint = \"counts\")\n",
        ),
        ("POST /api/workflows/transcriptomics/validate", 685, 688, f"b <- list(session_id = session_id, experiment = {exp})\n"),
        (
            "POST /api/workflows/transcriptomics/analyze/differential",
            697,
            726,
            f"""b <- list(
  session_id = session_id, experiment = {exp}, method = "DESeq2",
  group_var = NULL, ref_group = NULL, test_group = NULL,
  filter_low = TRUE, subset_two_groups = TRUE, cores = "auto"
)
""",
        ),
        (
            "POST /api/workflows/transcriptomics/analyze/gsea",
            735,
            754,
            f"b <- list(session_id = session_id, experiment = {exp}, database = \"KEGG\", organism = \"hsa\")\n",
        ),
        (
            "POST /api/workflows/transcriptomics/analyze/wgcna",
            763,
            783,
            f"b <- list(session_id = session_id, experiment = {exp}, method = \"spearman\", cutoff = 0.7)\n",
        ),
    ]
    for title, lo, hi, bpre in blocks:
        core = strip_json_inject(slurp(PL, lo, hi), bpre)
        parts.append(f"# --- {title} ---\n{core}")
    return "\n\n".join(parts)


def mgx_workflow_bundle() -> str:
    parts = [EXP_GUARD + "\n"]
    exp = "as.character(experiment)[1]"
    blocks: list[tuple[str, int, int, str]] = [
        ("POST /api/workflows/metagenomics/profile", 792, 797, f"b <- list(session_id = session_id, experiment = {exp}, id_type = \"auto\")\n"),
        ("POST /api/workflows/metagenomics/validate", 806, 811, f"b <- list(session_id = session_id, experiment = {exp}, id_type = \"auto\")\n"),
        (
            "POST /api/workflows/metagenomics/preprocess",
            819,
            826,
            f"b <- list(session_id = session_id, experiment = {exp}, max_na = 0.2, normalize_method = \"rclr\")\n",
        ),
        (
            "POST /api/workflows/metagenomics/analyze/differential",
            834,
            860,
            f"""b <- list(
  session_id = session_id, experiment = {exp}, id_type = "auto", method = "limma",
  group_var = NULL, ref_group = NULL, test_group = NULL
)
""",
        ),
        (
            "POST /api/workflows/metagenomics/analyze/enrichment",
            868,
            890,
            f"b <- list(session_id = session_id, experiment = {exp}, id_type = \"auto\", database = NULL, organism = \"hsa\")\n",
        ),
    ]
    for title, lo, hi, bpre in blocks:
        core = strip_json_inject(slurp(PL, lo, hi), bpre)
        parts.append(f"# --- {title} ---\n{core}")
    return "\n\n".join(parts)


def mbx_workflow_bundle() -> str:
    parts = [EXP_GUARD + "\n"]
    exp = "as.character(experiment)[1]"
    blocks: list[tuple[str, int, int, str]] = [
        ("POST /api/workflows/metabolomics/profile", 1508, 1512, f"b <- list(session_id = session_id, experiment = {exp})\n"),
        ("POST /api/workflows/metabolomics/validate", 1521, 1524, f"b <- list(session_id = session_id, experiment = {exp})\n"),
        (
            "POST /api/workflows/metabolomics/preprocess",
            1533,
            1547,
            f"b <- list(session_id = session_id, experiment = {exp}, max_na = NULL, impute_method = NULL, normalize_method = NULL)\n",
        ),
        (
            "POST /api/workflows/metabolomics/analyze/differential",
            1556,
            1571,
            f"b <- list(session_id = session_id, experiment = {exp}, method = NULL, group_var = NULL, ref_group = NULL, test_group = NULL)\n",
        ),
    ]
    for title, lo, hi, bpre in blocks:
        core = strip_json_inject(slurp(PL, lo, hi), bpre)
        parts.append(f"# --- {title} ---\n{core}")
    return "\n\n".join(parts)


def analysis_ana_cross_body() -> str:
    return strip_json_inject(
        slurp(PL, 2315, 2340),
        EXP_GUARD
        + """b <- list(
  session_id = session_id,
  exp_a = as.character(experiment)[1],
  exp_b = "REPLACE_SECOND_EXPERIMENT",
  traits = NULL, method = "spearman", top_n = 20L, clinical_source = "experiment"
)
""",
    )


def main() -> None:
    for fname, src, lo, hi, note, bpre in SLICES:
        body = strip_json_inject(slurp(src, lo, hi), bpre)
        write(fname, body, f"{note} — {src.name} lines {lo}-{hi}")

    for fname, src, lo, hi, note in VIZ_SLICES:
        write(fname, dedent_block(slurp(src, lo, hi)), f"{note} — {src.name} lines {lo}-{hi}")

    write(
        "visualization__viz-scatter.r.txt",
        VIZ_SCATTER_BODY,
        "viz.R make_scatter — calls server helper (double-circle points + projections)",
    )

    write("clinical__overview.r.txt", clinical_overview_body(), "clinical vars (GET) — hand-built from plumber.R")
    write("analysis__ana-tx.r.txt", tx_workflow_bundle(), "transcriptomics routes — bundled cores from plumber.R")
    write("analysis__ana-mgx.r.txt", mgx_workflow_bundle(), "metagenomics routes — bundled cores from plumber.R")
    write("analysis__ana-mbx.r.txt", mbx_workflow_bundle(), "metabolomics routes — bundled cores from plumber.R")
    write("analysis__ana-cross.r.txt", analysis_ana_cross_body(), "cross / multiomics joint — plumber.R lines 2315-2340")
    write("visualization__viz-tx.r.txt", tx_visual_bundle(), "tx heatmap + volcano — plumber.R")
    write("visualization__viz-mgx.r.txt", mgx_visual_bundle(), "mgx heatmap + volcano — plumber.R")


if __name__ == "__main__":
    main()
