# Note: $ErrorActionPreference is intentionally NOT set to "Stop" here.
# This script is called from bootstrap_and_start.ps1 which already wraps
# each step in error handling; we want clear Write-Error messages here
# without throwing on the first hiccup.

. "$PSScriptRoot\windows_r_utils.ps1"
Initialize-EMPPaths $PSScriptRoot
$Root = Get-EMPRepoRoot

$RuntimeConfig = Join-Path $Root "webapp\config\runtime.env"
if (Test-Path $RuntimeConfig) {
  Get-Content $RuntimeConfig | ForEach-Object {
    $line = $_.Trim()
    if (-not $line -or $line.StartsWith("#") -or -not $line.Contains("=")) { return }
    $parts = $line.Split("=", 2)
    $name = $parts[0].Trim()
    if ($name -and -not [Environment]::GetEnvironmentVariable($name, "Process")) {
      [Environment]::SetEnvironmentVariable($name, $parts[1].Trim(), "Process")
    }
  }
}

$ApiPort = if ($env:API_PORT) { $env:API_PORT } else { "8000" }
$WebPort = if ($env:WEB_PORT) { $env:WEB_PORT } else { "8080" }
$ApiHost = if ($env:API_HOST) { $env:API_HOST } else { "0.0.0.0" }
$WebHost = if ($env:WEB_HOST) { $env:WEB_HOST } else { "0.0.0.0" }
$EmpAllowedRoots = if ($env:EMP_ALLOWED_ROOTS) { $env:EMP_ALLOWED_ROOTS } else { Join-Path $Root "tests" }
$EmpEnableUserR = if ($env:EMP_ENABLE_USER_R) { $env:EMP_ENABLE_USER_R } else { "false" }
$EmpCorsOrigin = if ($env:EMP_CORS_ORIGIN) { $env:EMP_CORS_ORIGIN } else { "reflect-private" }
$EmpApiToken = if ($env:EMP_API_TOKEN) { $env:EMP_API_TOKEN } else { "" }
$RunDir = Join-Path $Root ".local_run"
$AuthJs = Join-Path $Root "webapp\frontend\js\runtime_auth.local.js"

function Test-EmpLoopbackHost([string]$HostName) {
  $h = ($HostName | ForEach-Object { $_.ToLowerInvariant() })
  return @("127.0.0.1", "localhost", "::1") -contains $h
}

if (-not (Test-EmpLoopbackHost $ApiHost)) {
  if (-not $EmpApiToken) {
    $bytes = New-Object byte[] 24
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $EmpApiToken = ($bytes | ForEach-Object { $_.ToString("x2") }) -join ""
    $env:EMP_API_TOKEN = $EmpApiToken
    if (Test-Path $RuntimeConfig) {
      $lines = Get-Content $RuntimeConfig
      $written = $false
      $newLines = foreach ($line in $lines) {
        if ($line -match '^EMP_API_TOKEN=') { $written = $true; "EMP_API_TOKEN=$EmpApiToken" } else { $line }
      }
      if (-not $written) { $newLines += "EMP_API_TOKEN=$EmpApiToken" }
      Set-Content -Path $RuntimeConfig -Value $newLines -Encoding utf8
    }
    Write-Host "Generated EMP_API_TOKEN for LAN/Tailscale access."
  }
  if (-not $EmpCorsOrigin -or $EmpCorsOrigin -eq "*") { $EmpCorsOrigin = "reflect-private" }
  $authDir = Split-Path -Parent $AuthJs
  New-Item -ItemType Directory -Force -Path $authDir | Out-Null
  Set-Content -Path $AuthJs -Value ("/* Generated by start_local_windows.ps1 */`nwindow.EMP_API_TOKEN = `"$EmpApiToken`";`n") -Encoding utf8
} else {
  if (Test-Path $AuthJs) { Remove-Item $AuthJs -Force -ErrorAction SilentlyContinue }
}

# Refresh PATH for any install that happened in a different PowerShell window
# or via winget in this session.
$env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" +
            [System.Environment]::GetEnvironmentVariable("Path","User")

$RscriptExe = Resolve-EMPRscriptExe
if (-not $RscriptExe) {
  Write-Host "[emp-error] Rscript.exe not found." -ForegroundColor Red
  Write-Host "  Install R, add its bin folder to PATH, or set one of:"
  Write-Host "    `$env:EMPI_RSCRIPT = 'D:\path\to\Rscript.exe'"
  Write-Host "    `$env:R_HOME      = 'D:\path\to\R-4.x.x'"
  Write-Host "  Or place R under: $(Join-Path (Split-Path -Parent $Root) 'R\R-4.x.x')"
  exit 1
}
Write-Host "Using Rscript: $RscriptExe"

$PythonCmd = Resolve-EMPPython
if (-not $PythonCmd) {
  Write-Host "[emp-error] Python 3 not found (needed to serve the web UI)." -ForegroundColor Red
  Write-Host "  Install it one of these ways, then re-run:"
  Write-Host "    winget install -e --id Python.Python.3.12"
  Write-Host "    or download from https://www.python.org/downloads/ (tick 'Add python.exe to PATH')"
  Write-Host "  Or point us at an existing interpreter:"
  Write-Host "    `$env:EMPI_PYTHON = 'C:\path\to\python.exe'"
  Write-Host "  Note: the Microsoft Store 'python' stub is ignored on purpose."
  exit 1
}
Write-Host "Using Python: $PythonCmd"

$ApiLog = Join-Path $RunDir "api.log"
$WebLog = Join-Path $RunDir "web.log"
$ApiPid = Join-Path $RunDir "api.pid"
$WebPid = Join-Path $RunDir "web.pid"

New-Item -ItemType Directory -Force -Path $RunDir | Out-Null

function Stop-PidFile($pidFile) {
  if (Test-Path $pidFile) {
    $pidValue = Get-Content $pidFile -ErrorAction SilentlyContinue
    if ($pidValue) {
      try { Stop-Process -Id ([int]$pidValue) -Force -ErrorAction SilentlyContinue } catch {}
    }
    Remove-Item $pidFile -Force -ErrorAction SilentlyContinue
  }
}

Stop-PidFile $ApiPid
Stop-PidFile $WebPid
Stop-EMPListenersOnPorts -Ports @([int]$ApiPort, [int]$WebPort)

$apiCmd = "cd `"$Root`"; `$env:API_HOST=`"$ApiHost`"; `$env:API_PORT=`"$ApiPort`"; `$env:EMP_ALLOWED_ROOTS=`"$EmpAllowedRoots`"; `$env:EMP_ENABLE_USER_R=`"$EmpEnableUserR`"; `$env:EMP_API_TOKEN=`"$EmpApiToken`"; `$env:EMP_CORS_ORIGIN=`"$EmpCorsOrigin`"; & `"$RscriptExe`" `"webapp/backend/run_api.R`" *> `"$ApiLog`""
$apiProc = Start-Process -FilePath "powershell" -ArgumentList "-NoProfile","-ExecutionPolicy","Bypass","-Command",$apiCmd -WindowStyle Hidden -PassThru
$apiProc.Id | Out-File -FilePath $ApiPid -Encoding ascii -Force

# Bind all interfaces so LAN / Tailscale clients can reach EMP.
$webCmd = "cd `"$Root`"; `$env:WEB_HOST=`"$WebHost`"; `$env:WEB_PORT=`"$WebPort`"; & `"$PythonCmd`" webapp/scripts/static_server.py $WebPort `"webapp/frontend`" `"$WebHost`" *> `"$WebLog`""
$webProc = Start-Process -FilePath "powershell" -ArgumentList "-NoProfile","-ExecutionPolicy","Bypass","-Command",$webCmd -WindowStyle Hidden -PassThru
$webProc.Id | Out-File -FilePath $WebPid -Encoding ascii -Force

# R + Bioconductor load can take 30–90s on first start; wait for API before opening the browser.
$healthUrl = "http://127.0.0.1:$ApiPort/api/health"
$deadline = (Get-Date).AddSeconds(120)
$apiReady = $false
while ((Get-Date) -lt $deadline) {
  try {
    $resp = Invoke-WebRequest -Uri $healthUrl -UseBasicParsing -TimeoutSec 3 -ErrorAction Stop
    if ($resp.StatusCode -eq 200) { $apiReady = $true; break }
  } catch { }
  Start-Sleep -Seconds 2
}
if (-not $apiReady) {
  $recentLog = if (Test-Path $ApiLog) {
    (Get-Content -Path $ApiLog -Tail 80 -ErrorAction SilentlyContinue) -join [Environment]::NewLine
  } else {
    "(API log was not created.)"
  }
  throw "API not ready after 120s.`nLog: $ApiLog`n$recentLog"
} else {
  Write-Host "API health OK: $healthUrl"
}
Start-Process "http://127.0.0.1:$WebPort/"
Write-Host "EasyMultiProfiler Web (本机): http://127.0.0.1:$WebPort"
Write-Host "API health (本机):            http://127.0.0.1:$ApiPort/api/health"
Write-Host "Bind: API $ApiHost:$ApiPort · Web $WebHost:$WebPort"
try {
  $lan = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object {
    $_.IPAddress -notlike '127.*' -and $_.PrefixOrigin -ne 'WellKnown'
  } | Select-Object -First 1 -ExpandProperty IPAddress)
  if ($lan) {
    Write-Host "Frontend (局域网): http://${lan}:$WebPort"
    Write-Host "API (局域网):      http://${lan}:$ApiPort/api/health"
  }
} catch {}
$ts = Get-Command tailscale -ErrorAction SilentlyContinue
if ($ts) {
  try {
    $tsIp = (& tailscale ip -4 2>$null | Select-Object -First 1)
    if ($tsIp) {
      Write-Host "Frontend (Tailscale): http://${tsIp}:$WebPort"
      Write-Host "API (Tailscale):      http://${tsIp}:$ApiPort/api/health"
    } else {
      Write-Host "Tailscale installed but offline. Run: tailscale up"
    }
  } catch {
    Write-Host "Tailscale installed but offline. Run: tailscale up"
  }
} else {
  Write-Host "Tailscale not found. Install from https://tailscale.com/download then: tailscale up"
}
