# Starts the Plumber backend and static frontend on Windows.
param(
  [switch]$NoBrowser,
  [ValidateRange(10, 600)][int]$StartupTimeoutSeconds = 180
)

$ErrorActionPreference = "Stop"

. "$PSScriptRoot\windows_r_utils.ps1"
Initialize-EMPPaths $PSScriptRoot
$Root = Get-EMPRepoRoot
Import-EMPRuntimeConfig

$ApiPort = if ($env:API_PORT) { $env:API_PORT } else { "8000" }
$WebPort = if ($env:WEB_PORT) { $env:WEB_PORT } else { "8080" }
$ApiHost = if ($env:API_HOST) { $env:API_HOST } else { "127.0.0.1" }
$WebHost = if ($env:WEB_HOST) { $env:WEB_HOST } else { "127.0.0.1" }
$EmpAllowedRoots = if ($env:EMP_ALLOWED_ROOTS) { $env:EMP_ALLOWED_ROOTS } else { Join-Path $Root "tests" }
$EmpEnableUserR = if ($env:EMP_ENABLE_USER_R) { $env:EMP_ENABLE_USER_R } else { "false" }
$EmpCorsOrigin = if ($env:EMP_CORS_ORIGIN) { $env:EMP_CORS_ORIGIN } else { "reflect-private" }
$EmpApiToken = if ($env:EMP_API_TOKEN) { $env:EMP_API_TOKEN } else { "" }
$RunDir = Join-Path $Root ".local_run"
$EmpDataDir = if ($env:EMP_DATA_DIR) { $env:EMP_DATA_DIR } else { Join-Path $RunDir "data" }
$AuthJs = Join-Path $Root "webapp\frontend\js\runtime_auth.local.js"

function Test-EmpLoopbackHost([string]$HostName) {
  $h = ($HostName | ForEach-Object { $_.ToLowerInvariant() })
  return @("127.0.0.1", "localhost", "::1") -contains $h
}

if (-not (Test-EmpLoopbackHost $ApiHost)) {
  if (-not $EmpApiToken) {
    $bytes = New-Object byte[] 24
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $EmpApiToken = ($bytes | ForEach-Object { $_.ToString("x2") }) -join ""
    $env:EMP_API_TOKEN = $EmpApiToken
    if (Test-Path $RuntimeConfig) {
      $lines = Get-Content $RuntimeConfig
      $written = $false
      $newLines = foreach ($line in $lines) {
        if ($line -match '^EMP_API_TOKEN=') { $written = $true; "EMP_API_TOKEN=$EmpApiToken" } else { $line }
      }
      if (-not $written) { $newLines += "EMP_API_TOKEN=$EmpApiToken" }
      Set-Content -Path $RuntimeConfig -Value $newLines -Encoding utf8
    }
    Write-Host "Generated EMP_API_TOKEN for LAN/Tailscale access."
  }
  if (-not $EmpCorsOrigin -or $EmpCorsOrigin -eq "*") { $EmpCorsOrigin = "reflect-private" }
  $authDir = Split-Path -Parent $AuthJs
  New-Item -ItemType Directory -Force -Path $authDir | Out-Null
  Set-Content -Path $AuthJs -Value ("/* Generated by start_local_windows.ps1 */`nwindow.EMP_API_TOKEN = `"$EmpApiToken`";`n") -Encoding utf8
} else {
  if (Test-Path $AuthJs) { Remove-Item $AuthJs -Force -ErrorAction SilentlyContinue }
}

# Refresh PATH for installs made in another window while preserving overrides
# already supplied by runtime.env or by the caller.
$machinePath = [System.Environment]::GetEnvironmentVariable("Path", "Machine")
$userPath = [System.Environment]::GetEnvironmentVariable("Path", "User")
$env:Path = (@($env:Path, $machinePath, $userPath) | Where-Object { $_ }) -join ";"

$RscriptExe = Resolve-EMPRscriptExe
if (-not $RscriptExe) {
  Write-Host "[emp-error] Rscript.exe not found." -ForegroundColor Red
  Write-Host "  Install R, add its bin folder to PATH, or set one of:"
  Write-Host "    `$env:EMPI_RSCRIPT = 'D:\path\to\Rscript.exe'"
  Write-Host "    `$env:R_HOME      = 'D:\path\to\R-4.x.x'"
  Write-Host "  Or place R under: $(Join-Path (Split-Path -Parent $Root) 'R\R-4.x.x')"
  exit 1
}
Write-Host "Using Rscript: $RscriptExe"

$PythonInfo = Resolve-EMPPython
if (-not $PythonInfo) {
  Write-Host "[emp-error] Python 3 not found (needed to serve the web UI)." -ForegroundColor Red
  Write-Host "  Install it one of these ways, then re-run:"
  Write-Host "    winget install -e --id Python.Python.3.12"
  Write-Host "    or download from https://www.python.org/downloads/ (tick 'Add python.exe to PATH')"
  Write-Host "  Or point us at an existing interpreter:"
  Write-Host "    `$env:EMPI_PYTHON = 'C:\path\to\python.exe'"
  Write-Host "  Note: the Microsoft Store 'python' stub is ignored on purpose."
  exit 1
}
Write-Host "Using Python: $(Format-EMPPythonDisplay $PythonInfo)"

$ApiLog = Join-Path $RunDir "api.log"
$WebLog = Join-Path $RunDir "web.log"
$ApiPid = Join-Path $RunDir "api.pid"
$WebPid = Join-Path $RunDir "web.pid"

New-Item -ItemType Directory -Force -Path $RunDir | Out-Null
New-Item -ItemType Directory -Force -Path $EmpDataDir | Out-Null

function Stop-PidFile($pidFile) {
  if (Test-Path $pidFile) {
    $pidValue = Get-Content $pidFile -ErrorAction SilentlyContinue
    if ($pidValue) {
      try { Stop-Process -Id ([int]$pidValue) -Force -ErrorAction SilentlyContinue } catch {}
    }
    Remove-Item $pidFile -Force -ErrorAction SilentlyContinue
  }
}

function Test-EmpHttpOk([string]$Url) {
  try {
    $resp = Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec 3 -ErrorAction Stop
    return ($resp.StatusCode -eq 200)
  } catch {
    return $false
  }
}

function Show-EmpTailLog([string]$Path, [string]$Label) {
  if (Test-Path $Path) {
    Write-Host "--- $Label (tail) ---"
    Get-Content -Path $Path -Tail 40 -ErrorAction SilentlyContinue | ForEach-Object { Write-Host $_ }
  } else {
    Write-Host "--- ${Label}: (log not created) ---"
  }
}

Stop-PidFile $ApiPid
Stop-PidFile $WebPid
Stop-EMPListenersOnPorts -Ports @([int]$ApiPort, [int]$WebPort)

# Inherit env into child processes (Start-Process does not take -Environment on older PS).
$env:API_HOST = $ApiHost
$env:API_PORT = "$ApiPort"
$env:WEB_HOST = $WebHost
$env:WEB_PORT = "$WebPort"
$env:EMP_ALLOWED_ROOTS = $EmpAllowedRoots
$env:EMP_ENABLE_USER_R = $EmpEnableUserR
$env:EMP_API_TOKEN = $EmpApiToken
$env:EMP_CORS_ORIGIN = $EmpCorsOrigin
$env:EMP_ROOT = $Root
$env:EMP_DATA_DIR = $EmpDataDir
$env:NO_PROXY = "*"
$env:no_proxy = "*"

Write-Host "Starting API + frontend together..."
$ApiErrLog = Join-Path $RunDir "api.err.log"
$WebErrLog = Join-Path $RunDir "web.err.log"
$apiScript = Join-Path $Root "webapp\backend\run_api.R"
# Direct Start-Process (not nested powershell) so both sides stay alive after the bat exits.
$apiArgs = @("--vanilla", (ConvertTo-EMPProcessArgument $apiScript))
$apiProc = Start-Process -FilePath $RscriptExe `
  -ArgumentList $apiArgs `
  -WorkingDirectory $Root `
  -WindowStyle Hidden `
  -RedirectStandardOutput $ApiLog `
  -RedirectStandardError $ApiErrLog `
  -PassThru
if (-not $apiProc) { throw "Failed to start API (Rscript)." }
$apiProc.Id | Out-File -FilePath $ApiPid -Encoding ascii -Force

$webArgs = @()
if ($PythonInfo.PrefixArgs) { $webArgs += $PythonInfo.PrefixArgs }
$webArgs += @(
  (ConvertTo-EMPProcessArgument (Join-Path $Root "webapp\scripts\static_server.py")),
  "$WebPort",
  (ConvertTo-EMPProcessArgument (Join-Path $Root "webapp\frontend")),
  "$WebHost"
)
$webProc = Start-Process -FilePath $PythonInfo.Exe `
  -ArgumentList $webArgs `
  -WorkingDirectory $Root `
  -WindowStyle Hidden `
  -RedirectStandardOutput $WebLog `
  -RedirectStandardError $WebErrLog `
  -PassThru
if (-not $webProc) { throw "Failed to start frontend (Python)." }
$webProc.Id | Out-File -FilePath $WebPid -Encoding ascii -Force

# Wait until BOTH are healthy before opening the browser (R load can take 30–90s).
$healthUrl = "http://127.0.0.1:$ApiPort/api/health"
$webUrl = "http://127.0.0.1:$WebPort/"
$deadline = (Get-Date).AddSeconds($StartupTimeoutSeconds)
$apiReady = $false
$webReady = $false
while ((Get-Date) -lt $deadline) {
  $apiProc.Refresh()
  $webProc.Refresh()
  if ($apiProc.HasExited) {
    Show-EmpTailLog $ApiLog "API stdout"
    Show-EmpTailLog $ApiErrLog "API stderr"
    throw "API process exited before becoming ready (exit $($apiProc.ExitCode))."
  }
  if ($webProc.HasExited) {
    Show-EmpTailLog $WebLog "Web stdout"
    Show-EmpTailLog $WebErrLog "Web stderr"
    throw "Frontend process exited before becoming ready (exit $($webProc.ExitCode))."
  }

  if (-not $apiReady) { $apiReady = Test-EmpHttpOk $healthUrl }
  if (-not $webReady) { $webReady = Test-EmpHttpOk $webUrl }
  if ($apiReady -and $webReady) { break }
  Start-Sleep -Seconds 1
}

if (-not $apiReady -or -not $webReady) {
  if (-not $apiReady) {
    Show-EmpTailLog $ApiLog "API stdout"
    Show-EmpTailLog $ApiErrLog "API stderr"
  }
  if (-not $webReady) {
    Show-EmpTailLog $WebLog "Web stdout"
    Show-EmpTailLog $WebErrLog "Web stderr"
  }
  throw "Startup incomplete after ${StartupTimeoutSeconds}s. API ready=$apiReady Frontend ready=$webReady"
}

Write-Host "API health OK:      $healthUrl"
Write-Host "Frontend OK:         $webUrl"
if (-not $NoBrowser -and $env:EMP_NO_BROWSER -ne "1") {
  Start-Process $webUrl
}
Write-Host "EasyMultiProfiler Web (本机): http://127.0.0.1:$WebPort"
Write-Host "API health (本机):            http://127.0.0.1:$ApiPort/api/health"
Write-Host "Bind: API ${ApiHost}:$ApiPort · Web ${WebHost}:$WebPort"
if (-not (Test-EmpLoopbackHost $ApiHost) -or -not (Test-EmpLoopbackHost $WebHost)) {
  try {
    $lan = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object {
      $_.IPAddress -notlike '127.*' -and $_.PrefixOrigin -ne 'WellKnown'
    } | Select-Object -First 1 -ExpandProperty IPAddress)
    if ($lan) {
      Write-Host "Frontend (局域网): http://${lan}:$WebPort"
      Write-Host "API (局域网):      http://${lan}:$ApiPort/api/health"
    }
  } catch {}
}
