#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RUNTIME_CONFIG="${ROOT_DIR}/webapp/config/runtime.env"
if [[ -f "${RUNTIME_CONFIG}" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${RUNTIME_CONFIG}"
  set +a
fi
API_PORT="${API_PORT:-8000}"
WEB_PORT="${WEB_PORT:-8080}"
# Bind all interfaces by default so LAN and Tailscale can reach EMP.
API_HOST="${API_HOST:-0.0.0.0}"
WEB_HOST="${WEB_HOST:-0.0.0.0}"
EMP_ALLOWED_ROOTS="${EMP_ALLOWED_ROOTS:-${ROOT_DIR}/tests}"
EMP_ENABLE_USER_R="${EMP_ENABLE_USER_R:-false}"
EMP_CORS_ORIGIN="${EMP_CORS_ORIGIN:-reflect-private}"
EMP_API_TOKEN="${EMP_API_TOKEN:-}"
# Auto-publish EMP on Tailscale Funnel HTTPS for phone / 外网 browsers.
EMP_ENABLE_FUNNEL="${EMP_ENABLE_FUNNEL:-true}"
GATEWAY_PORT="${GATEWAY_PORT:-8090}"
PIDS_DIR="${ROOT_DIR}/.local_run"
API_PID_FILE="${PIDS_DIR}/api.pid"
WEB_PID_FILE="${PIDS_DIR}/web.pid"
GW_PID_FILE="${PIDS_DIR}/gateway.pid"
API_LOG="${PIDS_DIR}/api.log"
WEB_LOG="${PIDS_DIR}/web.log"
GW_LOG="${PIDS_DIR}/gateway.log"
AUTH_JS="${ROOT_DIR}/webapp/frontend/js/runtime_auth.local.js"

mkdir -p "${PIDS_DIR}"

is_loopback_host() {
  case "$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')" in
    127.0.0.1|localhost|::1) return 0 ;;
    *) return 1 ;;
  esac
}

ensure_network_auth() {
  if is_loopback_host "${API_HOST}"; then
    # Loopback-only: clear generated auth file so UI stays token-free.
    rm -f "${AUTH_JS}"
    return 0
  fi
  if [[ -z "${EMP_API_TOKEN}" ]]; then
    if command -v openssl >/dev/null 2>&1; then
      EMP_API_TOKEN="$(openssl rand -hex 24)"
    else
      EMP_API_TOKEN="$(python3 -c 'import secrets; print(secrets.token_hex(24))')"
    fi
    if [[ -f "${RUNTIME_CONFIG}" ]]; then
      if grep -q '^EMP_API_TOKEN=' "${RUNTIME_CONFIG}" 2>/dev/null; then
        tmp="$(mktemp)"
        awk -v tok="${EMP_API_TOKEN}" '
          BEGIN { done=0 }
          /^EMP_API_TOKEN=/ { print "EMP_API_TOKEN=" tok; done=1; next }
          { print }
          END { if (!done) print "EMP_API_TOKEN=" tok }
        ' "${RUNTIME_CONFIG}" > "${tmp}"
        mv "${tmp}" "${RUNTIME_CONFIG}"
      else
        printf '\nEMP_API_TOKEN=%s\n' "${EMP_API_TOKEN}" >> "${RUNTIME_CONFIG}"
      fi
    fi
    echo "Generated EMP_API_TOKEN for LAN/Tailscale access (saved in runtime.env)."
  fi
  if [[ -z "${EMP_CORS_ORIGIN}" || "${EMP_CORS_ORIGIN}" == "*" ]]; then
    EMP_CORS_ORIGIN="reflect-private"
  fi
  if [[ -f "${RUNTIME_CONFIG}" ]] && ! grep -q '^EMP_CORS_ORIGIN=' "${RUNTIME_CONFIG}" 2>/dev/null; then
    printf 'EMP_CORS_ORIGIN=%s\n' "${EMP_CORS_ORIGIN}" >> "${RUNTIME_CONFIG}"
  fi
  mkdir -p "$(dirname "${AUTH_JS}")"
  cat > "${AUTH_JS}" <<EOF
/* Generated by start_local.sh — do not commit. Bearer token for LAN/Tailscale. */
window.EMP_API_TOKEN = "${EMP_API_TOKEN}";
EOF
}

ensure_network_auth

kill_if_running() {
  local pid_file="$1"
  if [[ -f "${pid_file}" ]]; then
    local pid
    pid="$(cat "${pid_file}" 2>/dev/null || true)"
    if [[ -n "${pid}" ]] && kill -0 "${pid}" 2>/dev/null; then
      kill "${pid}" || true
    fi
    rm -f "${pid_file}"
  fi
}

kill_if_running "${API_PID_FILE}"
kill_if_running "${WEB_PID_FILE}"
kill_if_running "${GW_PID_FILE}"

kill_port_if_running() {
  local port="$1"
  local attempt pids
  for attempt in 1 2 3; do
    pids="$(lsof -t -iTCP:"${port}" -sTCP:LISTEN 2>/dev/null || true)"
    if [[ -z "${pids}" ]]; then
      return 0
    fi
    # shellcheck disable=SC2086
    kill ${pids} 2>/dev/null || true
    sleep 1
    pids="$(lsof -t -iTCP:"${port}" -sTCP:LISTEN 2>/dev/null || true)"
    if [[ -n "${pids}" ]]; then
      # shellcheck disable=SC2086
      kill -9 ${pids} 2>/dev/null || true
      sleep 1
    fi
  done
  if lsof -t -iTCP:"${port}" -sTCP:LISTEN >/dev/null 2>&1; then
    echo "Port ${port} is still in use after cleanup. Try: lsof -iTCP:${port} -sTCP:LISTEN" >&2
    return 1
  fi
}

# Ensure stale listeners do not block new instances.
kill_port_if_running "${API_PORT}"
kill_port_if_running "${WEB_PORT}"
kill_port_if_running "${GATEWAY_PORT}"

start_detached() {
  local pid_file="$1"
  local log_file="$2"
  shift 2
  # Always detach via nohup+bash so the recorded PID is the long-lived child
  # (macOS has no setsid; bare `env ... &` can leave a short-lived wrapper PID
  # and the API later gets reaped when the launcher shell exits).
  nohup bash -c 'exec "$@"' _ "$@" >"${log_file}" 2>&1 < /dev/null &
  echo $! > "${pid_file}"
}

detect_lan_ip() {
  local ip=""
  if command -v ipconfig >/dev/null 2>&1; then
    for iface in en0 en1 en2 en3; do
      ip="$(ipconfig getifaddr "${iface}" 2>/dev/null || true)"
      if [[ -n "${ip}" ]]; then
        echo "${ip}"
        return 0
      fi
    done
  fi
  if command -v hostname >/dev/null 2>&1; then
    ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
    if [[ -n "${ip}" ]]; then
      echo "${ip}"
      return 0
    fi
  fi
  return 1
}

detect_tailscale_ip() {
  if ! command -v tailscale >/dev/null 2>&1; then
    return 1
  fi
  local ip
  ip="$(tailscale ip -4 2>/dev/null | head -n1 || true)"
  if [[ -n "${ip}" ]]; then
    echo "${ip}"
    return 0
  fi
  return 1
}

detect_tailscale_name() {
  if ! command -v tailscale >/dev/null 2>&1; then
    return 1
  fi
  local name
  name="$(tailscale status --json 2>/dev/null | python3 -c 'import json,sys
try:
  d=json.load(sys.stdin)
  print(d.get("Self",{}).get("DNSName","").rstrip("."))
except Exception:
  pass' 2>/dev/null || true)"
  if [[ -n "${name}" ]]; then
    echo "${name}"
    return 0
  fi
  return 1
}

print_access_urls() {
  local lan_ip ts_ip ts_name
  echo "Local services started."
  echo "- Frontend (本机):     http://127.0.0.1:${WEB_PORT}"
  echo "- API health (本机):   http://127.0.0.1:${API_PORT}/api/health"
  lan_ip="$(detect_lan_ip || true)"
  if [[ -n "${lan_ip}" ]]; then
    echo "- Frontend (局域网):   http://${lan_ip}:${WEB_PORT}"
    echo "- API health (局域网): http://${lan_ip}:${API_PORT}/api/health"
  fi
  ts_ip="$(detect_tailscale_ip || true)"
  ts_name="$(detect_tailscale_name || true)"
  if [[ -n "${ts_ip}" ]]; then
    echo "- Frontend (Tailscale): http://${ts_ip}:${WEB_PORT}"
    echo "- API health (Tailscale): http://${ts_ip}:${API_PORT}/api/health"
    if [[ -n "${ts_name}" ]]; then
      echo "- Frontend (MagicDNS):  http://${ts_name}:${WEB_PORT}"
    fi
  else
    if command -v tailscale >/dev/null 2>&1; then
      echo "- Tailscale: 已安装但未上线。外网访问请先运行: tailscale up"
    else
      echo "- Tailscale: 未安装。外网访问请安装后运行: tailscale up"
      echo "  https://tailscale.com/download"
    fi
  fi
  echo "- Bind: API ${API_HOST}:${API_PORT} · Web ${WEB_HOST}:${WEB_PORT}"
  if ! is_loopback_host "${API_HOST}"; then
    echo "- Auth: EMP_API_TOKEN 已启用（浏览器自动加载 runtime_auth.local.js）"
    echo "- CORS: ${EMP_CORS_ORIGIN}"
  fi
  if [[ -n "${FUNNEL_URL:-}" ]]; then
    echo "- 外网手机（Funnel HTTPS）: ${FUNNEL_URL}"
  fi
  echo "- Logs: ${API_LOG}, ${WEB_LOG}"
}

start_gateway_and_funnel() {
  FUNNEL_URL=""
  case "$(printf '%s' "${EMP_ENABLE_FUNNEL}" | tr '[:upper:]' '[:lower:]')" in
    1|true|yes|on) ;;
    *) return 0 ;;
  esac
  if ! command -v tailscale >/dev/null 2>&1; then
    echo "Tip: install Tailscale for phone/外网 Funnel access."
    return 0
  fi
  if ! curl_ok "http://127.0.0.1:${WEB_PORT}/" || ! curl_ok "http://127.0.0.1:${API_PORT}/api/health"; then
    return 0
  fi

  echo "Starting EMP gateway on 127.0.0.1:${GATEWAY_PORT} ..."
  start_detached "${GW_PID_FILE}" "${GW_LOG}" \
    env API_PORT="${API_PORT}" WEB_PORT="${WEB_PORT}" GATEWAY_PORT="${GATEWAY_PORT}" GATEWAY_HOST=127.0.0.1 \
    "${PY}" webapp/scripts/emp_gateway.py
  sleep 1
  if ! curl_ok "http://127.0.0.1:${GATEWAY_PORT}/api/health"; then
    echo "Gateway failed; Funnel not updated. See ${GW_LOG}"
    return 0
  fi

  if ! tailscale status >/dev/null 2>&1; then
    echo "Tailscale offline. Run: sudo tailscale up"
    echo "Then: bash webapp/scripts/enable_emp_funnel.sh"
    return 0
  fi

  echo "Pointing Tailscale Funnel HTTPS:443 -> EMP gateway :${GATEWAY_PORT} ..."
  # Do NOT `funnel reset` — preserve other Funnel ports (e.g. :8443 Agent Hub).
  if tailscale funnel --bg --yes --https=443 "${GATEWAY_PORT}" >/dev/null 2>&1; then
    FUNNEL_URL="$(tailscale status --json 2>/dev/null | python3 -c 'import json,sys
d=json.load(sys.stdin)
name=(d.get("Self",{}) or {}).get("DNSName","").rstrip(".")
print(f"https://{name}/" if name else "")' 2>/dev/null || true)"
    # Keep Agent Hub on Funnel :8443 when local hub is up (optional companion service).
    if curl_ok "http://127.0.0.1:8765/"; then
      tailscale funnel --bg --yes --https=8443 8765 >/dev/null 2>&1 || true
    fi
  else
    echo "Funnel enable failed. Try manually: bash webapp/scripts/enable_emp_funnel.sh"
  fi
}

echo "Starting API on ${API_HOST}:${API_PORT} ..."
cd "${ROOT_DIR}"
# Prefer project-local R libs (e.g. dplyr 1.1.4) so EMP/bootnet still load if
# system dplyr≥1.2 dropped exports like dplyr::id.
LOCAL_R_LIBS="${PIDS_DIR}/R_libs"
if [[ -d "${LOCAL_R_LIBS}" ]]; then
  export R_LIBS="${LOCAL_R_LIBS}${R_LIBS:+:${R_LIBS}}"
  export R_LIBS_USER="${LOCAL_R_LIBS}${R_LIBS_USER:+:${R_LIBS_USER}}"
fi
# deepTools / MACS3 (and other CLI tools) installed under .local_run for EMP ChIP-seq.
LOCAL_BIN="${PIDS_DIR}/bin"
LOCAL_DT_BIN="${PIDS_DIR}/deeptools_venv/bin"
LOCAL_MACS_BIN="${PIDS_DIR}/macs_venv/bin"
PATH_PREFIX=""
if [[ -d "${LOCAL_BIN}" ]]; then PATH_PREFIX="${LOCAL_BIN}"; fi
if [[ -d "${LOCAL_DT_BIN}" ]]; then
  PATH_PREFIX="${PATH_PREFIX:+${PATH_PREFIX}:}${LOCAL_DT_BIN}"
fi
if [[ -d "${LOCAL_MACS_BIN}" ]]; then
  PATH_PREFIX="${PATH_PREFIX:+${PATH_PREFIX}:}${LOCAL_MACS_BIN}"
fi
if [[ -n "${PATH_PREFIX}" ]]; then
  export PATH="${PATH_PREFIX}:${PATH}"
fi
export EMP_ROOT="${ROOT_DIR}"
if [[ -z "${EMP_DEEPTOOLS_BIN:-}" && -d "${LOCAL_DT_BIN}" ]]; then
  export EMP_DEEPTOOLS_BIN="${LOCAL_DT_BIN}"
fi
if [[ -z "${EMP_MACS_BIN:-}" && -d "${LOCAL_BIN}" && -x "${LOCAL_BIN}/macs3" ]]; then
  export EMP_MACS_BIN="${LOCAL_BIN}"
elif [[ -z "${EMP_MACS_BIN:-}" && -d "${LOCAL_MACS_BIN}" ]]; then
  export EMP_MACS_BIN="${LOCAL_MACS_BIN}"
fi
start_detached "${API_PID_FILE}" "${API_LOG}" \
  env API_HOST="${API_HOST}" API_PORT="${API_PORT}" \
    EMP_ALLOWED_ROOTS="${EMP_ALLOWED_ROOTS}" EMP_ENABLE_USER_R="${EMP_ENABLE_USER_R}" \
    EMP_API_TOKEN="${EMP_API_TOKEN}" EMP_CORS_ORIGIN="${EMP_CORS_ORIGIN}" \
    EMP_ROOT="${EMP_ROOT}" EMP_DEEPTOOLS_BIN="${EMP_DEEPTOOLS_BIN:-}" \
    EMP_MACS_BIN="${EMP_MACS_BIN:-}" \
    PATH="${PATH}" \
    R_LIBS="${R_LIBS:-}" R_LIBS_USER="${R_LIBS_USER:-}" \
    NO_PROXY='*' no_proxy='*' Rscript "webapp/backend/run_api.R"

echo "Starting frontend on ${WEB_HOST}:${WEB_PORT} ..."
PY=""
for _py in python3 python; do
  if command -v "${_py}" >/dev/null 2>&1; then
    PY="${_py}"
    break
  fi
done
if [[ -z "${PY}" ]]; then
  echo "Python 3 not found. Mac: brew install python@3.12" >&2
  exit 1
fi
start_detached "${WEB_PID_FILE}" "${WEB_LOG}" \
  env WEB_HOST="${WEB_HOST}" WEB_PORT="${WEB_PORT}" \
  "${PY}" webapp/scripts/static_server.py "${WEB_PORT}" "webapp/frontend" "${WEB_HOST}"

web_pid="$(cat "${WEB_PID_FILE}" 2>/dev/null || true)"
if [[ -z "${web_pid}" ]] || ! kill -0 "${web_pid}" 2>/dev/null; then
  echo "Frontend process exited immediately. Recent log:" >&2
  tail -n 40 "${WEB_LOG}" >&2 || true
  exit 1
fi

curl_ok() {
  curl --noproxy '*' -fsS --retry 2 --retry-connrefused --retry-delay 1 --max-time 5 "$1" >/dev/null 2>&1
}

api_failed_in_log() {
  [[ -f "${API_LOG}" ]] && grep -Eiq '(^|[^a-z])(error in|execution halted|cannot open|failed to start)' "${API_LOG}"
}

wait_for_services() {
  local max_attempts="${1:-120}"
  local attempt api_ok web_ok
  for attempt in $(seq 1 "${max_attempts}"); do
    api_ok=1
    web_ok=1
    curl_ok "http://127.0.0.1:${API_PORT}/api/health" && api_ok=0
    curl_ok "http://127.0.0.1:${WEB_PORT}/" && web_ok=0
    if [[ "${api_ok}" -eq 0 && "${web_ok}" -eq 0 ]]; then
      return 0
    fi
    if api_failed_in_log; then
      echo "API failed while starting. Recent log:"
      tail -n 80 "${API_LOG}" || true
      return 1
    fi
    web_pid="$(cat "${WEB_PID_FILE}" 2>/dev/null || true)"
    if [[ -z "${web_pid}" ]] || ! kill -0 "${web_pid}" 2>/dev/null; then
      echo "Frontend process exited while starting. Recent log:"
      tail -n 80 "${WEB_LOG}" || true
      return 1
    fi
    sleep 1
  done
  if [[ "${api_ok}" -ne 0 ]]; then
    echo "API did not become ready after ${max_attempts}s. Recent log:"
    tail -n 80 "${API_LOG}" || true
  fi
  if [[ "${web_ok}" -ne 0 ]]; then
    echo "Frontend did not become ready after ${max_attempts}s. Recent log:"
    tail -n 80 "${WEB_LOG}" || true
  fi
  return 1
}

wait_for_services 120
start_gateway_and_funnel
print_access_urls
